# Generated by Django 3.1.1 on 2020-10-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='parent_board',
            new_name='parent_list',
        ),
    ]
